// Generated by `opennextjs-cloudflare build` before Wrangler bundles this entrypoint.
// @ts-ignore The generated module is intentionally absent in a clean checkout.
import openNextWorker from "./.open-next/worker.js";

type WorkerEnv = Record<string, unknown> & { CRON_SECRET?: string };
type WorkerContext = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: openNextWorker.fetch,
  async scheduled(_controller: { cron: string }, env: WorkerEnv, ctx: WorkerContext) {
    if (!env.CRON_SECRET) {
      console.error("Reconciliation reminder skipped: CRON_SECRET is not configured");
      return;
    }
    const request = new Request("https://goko.internal/api/cron/reconciliation-reminder", {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await openNextWorker.fetch(request, env, ctx);
    if (!response.ok) {
      console.error(`Reconciliation reminder failed: ${response.status} ${await response.text()}`);
    }
  },
};
