-- Website CMS tables + seed of current events / community content

CREATE TABLE IF NOT EXISTS site_events (
  id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  date text NOT NULL DEFAULT '',
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  tags text NOT NULL DEFAULT '[]',
  is_past integer NOT NULL DEFAULT 0,
  cover_url text NOT NULL DEFAULT '',
  photos text NOT NULL DEFAULT '[]',
  display_order integer NOT NULL DEFAULT 0,
  updated_at text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_site_events_past_order ON site_events (is_past, display_order);

CREATE TABLE IF NOT EXISTS site_community_spaces (
  id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  title text NOT NULL,
  icon text NOT NULL DEFAULT 'sofa',
  description text NOT NULL DEFAULT '',
  image_url text NOT NULL DEFAULT '',
  photos text NOT NULL DEFAULT '[]',
  display_order integer NOT NULL DEFAULT 0,
  updated_at text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_site_community_spaces_order ON site_community_spaces (display_order);

CREATE TABLE IF NOT EXISTS site_page_copy (
  page text PRIMARY KEY NOT NULL,
  content text NOT NULL DEFAULT '{}',
  updated_at text NOT NULL DEFAULT ''
);

INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('September 2026', 'Ganesha Chaturthi Celebration', 'Honor Lord Ganesha with traditional puja, modak making workshop, devotional music, and beach immersion ceremony. Experience authentic Indian spirituality!', '["Puja ceremony","Modak workshop","Devotional music"]', 0, '/images/mahabaleshwar_temple.jpg', '["/images/mahabaleshwar_temple.jpg"]', 0, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('Monthly', 'Full Moon Beach Parties', 'Monthly celebration under the full moon! Dance barefoot on the beach with live DJ, bonfire, beach games, and magical moon energy. Every full moon, we celebrate!', '["Live DJ","Bonfire","Beach games"]', 0, '/images/IMG_3347.jpg', '["/images/IMG_3347.jpg"]', 1, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('October 31, 2026', 'Halloween Spooktacular', 'Get spooky at Goko! Costume contest, horror movie marathon, pumpkin carving, themed cocktails, and a haunted beach walk. Best costume wins a prize!', '["Costume contest","Pumpkin carving","Movie marathon"]', 0, '/images/goko-haloween-2024/IMG_7128.jpg', '["/images/goko-haloween-2024/IMG_7128.jpg"]', 2, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('December 31, 2026', 'New Year''s Eve Beach Party', 'Ring in the new year with your Goko family! Countdown on the beach with DJ, fireworks, dancing, and unlimited good vibes. Let''s welcome 2027 together!', '["Fireworks","DJ night","Cocktails"]', 0, '/images/goko-haloween-2024/IMG_7257.jpg', '["/images/goko-haloween-2024/IMG_7257.jpg"]', 3, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('March 8, 2024', 'Holi 2024 - Epic Color Battle!', 'Our first Holi celebration was absolutely epic! Over 80 guests joined for an unforgettable color festival. The beach turned into a rainbow paradise!', '["80+ participants","Huge success"]', 1, '/images/goko-holi-2024/IMG_6046.jpg', '["/images/goko-holi-2024/IMG_6046.jpg"]', 0, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('November 12, 2023', 'Diwali - Festival of Lights', 'Our inaugural Diwali celebration! Decorated the entire hostel with diyas, hosted a traditional puja, shared sweets, and lit up the beach with sparklers. Magical night!', '["Traditional puja","Sparklers","Sweets"]', 1, '/images/goko-deepawali-2024/IMG_3985.jpg', '["/images/goko-deepawali-2024/IMG_3985.jpg"]', 1, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('December 25, 2023', 'Christmas 2023 Beach Celebration', 'Celebrated Christmas with our international hostel family! Palm tree decorations, beach bonfire, carol singing, Secret Santa gifts, and a feast to remember.', '["Secret Santa","Beach bonfire","Carol singing"]', 1, '/images/goko-deepawali-2024/IMG_5486.jpg', '["/images/goko-deepawali-2024/IMG_5486.jpg"]', 2, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('September 19, 2023', 'Ganesha Chaturthi 2023', 'Beautiful celebration honoring Lord Ganesha! Morning puja, made eco-friendly clay idols, cooked modaks together, and did a peaceful beach immersion ceremony.', '["Traditional puja","Beach immersion","Eco-friendly"]', 1, '/images/mahabaleshwar_temple.jpg', '["/images/mahabaleshwar_temple.jpg"]', 3, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('October 31, 2023', 'Halloween 2023 - Spooky Beach Night', 'Our first Halloween was a scream! Amazing costumes, spooky decorations, thriller dance performance, pumpkin carving competition, and ghostly beach tales.', '["Best costume award","Thriller dance","Ghost stories"]', 1, '/images/goko-haloween-2024/FullSizeRender.jpg', '["/images/goko-haloween-2024/FullSizeRender.jpg"]', 4, '2026-08-28T00:00:00.000Z');
INSERT INTO site_events (date, title, description, tags, is_past, cover_url, photos, display_order, updated_at) VALUES ('August 15, 2023', 'Independence Day Celebration', 'Celebrated India''s Independence Day with flag hoisting, cultural performances, traditional games, Indian breakfast feast, and stories about freedom fighters!', '["Flag hoisting","Cultural show","Indian feast"]', 1, '/images/IMG_3413.jpg', '["/images/IMG_3413.jpg"]', 5, '2026-08-28T00:00:00.000Z');

INSERT INTO site_community_spaces (title, icon, description, image_url, photos, display_order, updated_at) VALUES ('The lounge', 'sofa', 'Cozy seating, plenty of cushions, and a laid-back vibe. Perfect for reading, chatting, or simply relaxing after a day at the beach. Our lounge is your second living room.', '/images/community-area/lounge/common-area5.jpg', '["/images/community-area/lounge/common-area5.jpg"]', 0, '2026-08-28T00:00:00.000Z');
INSERT INTO site_community_spaces (title, icon, description, image_url, photos, display_order, updated_at) VALUES ('Communal dining', 'utensils', 'Share meals around our large communal table. Some of the best friendships start over breakfast or a shared dinner. We often host community dinners and potlucks!', '/images/goko-common-area/IMG_7024.JPG', '["/images/goko-common-area/IMG_7024.JPG"]', 1, '2026-08-28T00:00:00.000Z');
INSERT INTO site_community_spaces (title, icon, description, image_url, photos, display_order, updated_at) VALUES ('Games corner', 'dice', 'Board games, cards, chess, and more! Challenge fellow travelers to a game or join our weekly game nights. Competitive spirits welcome!', '/images/community-area/games/common-area5.jpg', '["/images/community-area/games/common-area5.jpg"]', 2, '2026-08-28T00:00:00.000Z');
INSERT INTO site_community_spaces (title, icon, description, image_url, photos, display_order, updated_at) VALUES ('Co-working space', 'laptop', 'Need to catch up on work? Our quiet co-working area offers fast WiFi, comfortable seating, and a productive atmosphere for digital nomads.', '/images/community-area/workspace/Screenshot%20at%20Dec%2006%2022-19-37.jpg', '["/images/community-area/workspace/Screenshot%20at%20Dec%2006%2022-19-37.jpg"]', 3, '2026-08-28T00:00:00.000Z');
INSERT INTO site_community_spaces (title, icon, description, image_url, photos, display_order, updated_at) VALUES ('Book exchange', 'book', 'A carefully curated collection of travel stories, novels, and local guides. Take a book, leave a book, share your favorite reads with fellow travelers.', '/images/community-area/book-exchange/Screenshot%20at%20Dec%2006%2022-19-37.jpg', '["/images/community-area/book-exchange/Screenshot%20at%20Dec%2006%2022-19-37.jpg"]', 4, '2026-08-28T00:00:00.000Z');

INSERT INTO site_page_copy (page, content, updated_at) VALUES ('events', '{"hero":{"title":"Events at Goko Hostel","subtitle":"Join our vibrant community for festivals, celebrations, and unforgettable experiences by the beach in Gokarna!","chips":["🎊 Festivals","🎵 Live music","🌊 Beach parties","🪔 Cultural events"],"ribbonImage":"/images/goko-holi-2024/IMG_6047.jpg"},"pastCta":{"title":"Don''t miss out!","body":"Want to join our next celebration? Book your stay at Goko Hostel and be part of our amazing community events!"}}', '2026-08-28T00:00:00.000Z');
INSERT INTO site_page_copy (page, content, updated_at) VALUES ('community', '{"hero":{"title":"Goko Community Area","subtitle":"Where strangers become friends, and friends become family. Welcome to the heart of Goko.","ribbonImage":"/legacy-images/62f5bf7bfc22850018b36726-63021b52b4a9f5776b671ae4_home_video-thumbnail_2.webp"},"intro":{"title":"More than just a common area","paragraph":"Our community area is the beating heart of Goko Hostel — where travelers gather to share stories, play games, enjoy meals together, and create memories that last a lifetime. Whether you unwind with a book, play chess, or join an event, there''s always something happening here."},"activities":{"title":"Activities & games","subtitle":"There''s always something fun happening at Goko!","badges":["Board games","Chess & checkers","Card games","Music jam sessions","Cooking together","Movie nights","Bonfire stories","Open mic nights","Art & craft","Book club"],"rhythmTitle":"Weekly rhythm","rhythmIntro":"Join us for community dinners, game nights, movie screenings, and spontaneous adventures. At Goko, every day is an opportunity to meet amazing people from around the world.","weekly":[{"label":"Monday","text":"Game night — board games, cards, and friendly competition"},{"label":"Tuesday","text":"Community dinner — potluck style, everyone brings something!"},{"label":"Wednesday","text":"Just do nothing — sip a coconut and chill"},{"label":"Thursday","text":"Movie night — classic films and travel documentaries"},{"label":"Friday","text":"Open mic night — share your talent, poetry, or stories"},{"label":"Saturday","text":"Beach day — group trips to Gokarna''s beautiful beaches"},{"label":"Sunday","text":"Sunset sessions — music, conversations, and chill vibes"}]},"specialEvents":{"title":"Special events","subtitle":"Beyond the everyday, we celebrate together","cards":[{"title":"Festival celebrations","description":"From Holi to Christmas, Halloween to Diwali — we celebrate cultures from around the world. Join us for colorful festivals, traditional foods, and unforgettable memories!"},{"title":"Workshops & classes","description":"Learn something new! We host workshops on everything from local cooking to meditation, photography to sustainable travel. Share your skills or learn from others."},{"title":"Cultural exchanges","description":"With travelers from all corners of the globe, every day is a cultural exchange. Share your traditions, learn about others, and expand your worldview."},{"title":"Bonfires & barbecue","description":"Evening bonfires paired with easygoing barbecue feasts—grill-side chats, guitars, and good company. Some of our best memories spark when the coals are still warm."}]}}', '2026-08-28T00:00:00.000Z');
